spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xwtmteacher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: 123456
    druid:
      max-active: 15
      initial-size: 5
      min-idle: 3
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
  redis:
    database: 1
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  type-aliases-package: com.guo.pojo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl