eureka:
  client:
    service-url:
      defaultZone: http://localhost:12345/eureka

#hystrix的超时时间
hystrix:
  command:
    default:
      timeout:
        enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 8000

#ribbon的超时时间
ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000
